BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  devise_for :users
  resources :users, only: [:show] do
    member do
      get 'my_challenges', to: 'challenges#my_challenges'
    end
  end
  resources :users, only: [:show]
  resources :disputes, only: [:new]
  resources :deposits, only: [:new, :create] do
    resources :payments, only: [:new, :create]
  end
  resources :challenges do
    get 'host_win', to: 'challenges#host_win', as: :host_win
    get 'host_lost', to: 'challenges#host_lost', as: :host_lost
    get 'set_guest', to: 'challenges#set_guest', as: :set_guest
    get 'guest_left', to: 'challenges#guest_left', as: :guest_left
    member do
      patch 'add_time', to: 'challenges#add_time'
      patch 'leave', to: 'challenges#leave'
    end
  end
  resources :chatrooms do
    resources :messages
  end
  resources :activities

  mount ActionCable.server => "/cable"
  #do
  #  resources :disputes, only: [:new, :create, :show, :delete]
  #end
  # post '/challenges/:id/', to: 'challenges#set_guest', as:
end

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  end

  def create
    @deposit = Deposit.find(params[:deposit_id])
    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @deposit.amount_cents,
    description:  "deposit for BettrPlay",
    currency:     current_user.balance.currency
  )
  @deposit.update(payment: charge.to_json, state: 'paid')
  current_user.balance_cents += @deposit.amount_cents
  current_user.save
  redirect_to challenges_path

  rescue Stripe::CardError => e
  flash[:alert] = e.message
  redirect_to new_deposit_payment_path(@deposit)
  end

end

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/payments/new.html.erb
<% @deposit = Deposit.find(params[:deposit_id]) %>
  <div class="container-deposit">


  <%= form_tag deposit_payments_path(@deposit) do %>
    <h1>Deposit confirmation</h1>
    <div class="deposit-form-container">
      <div class="deposit-form">
          <div class="thirddiv">
            <p>You are depositing:</p>
            <label class="amount">
                <span><%= humanized_money_with_symbol(@deposit.amount) %></span>
            </label>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-name="Deposit"
              data-email="<%= current_user.email %>"
              data-description="BettrPlay Deposit"
              data-amount="<%= @deposit.amount_cents %>"
              data-currency="<%= @deposit.amount.currency %>"></script>
          </div>
      </div>
    </div>
      <img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/SNES-controller.png" alt="">
  </div>
<% end %>