BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  devise_for :users
  resources :users, only: [:show] do
    member do
      get 'my_challenges', to: 'challenges#my_challenges'
    end
  end
  resources :users, only: [:show]
  resources :disputes, only: [:new]
  resources :deposits, only: [:new, :create] do
    resources :payments, only: [:new, :create]
  end
  resources :challenges do
    get 'host_win', to: 'challenges#host_win', as: :host_win
    get 'host_lost', to: 'challenges#host_lost', as: :host_lost
    get 'set_guest', to: 'challenges#set_guest', as: :set_guest
    get 'guest_left', to: 'challenges#guest_left', as: :guest_left
    member do
      patch 'add_time', to: 'challenges#add_time'
      patch 'leave', to: 'challenges#leave'
    end
  end
  resources :chatrooms do
    resources :messages
  end
  resources :activities

  mount ActionCable.server => "/cable"
  #do
  #  resources :disputes, only: [:new, :create, :show, :delete]
  #end
  # post '/challenges/:id/', to: 'challenges#set_guest', as:
end

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_card.html.erb
<a href="/challenges/<%= challenge.id %>">
  <div class="card">
    <div class="card-body" style="background-image: linear-gradient(-225deg, rgba(255,255,255,0.5) 0%, rgba(255,255,255,0.5) 50%), url(<%= challenge.photo %>);">
      <div class="card-platform">
        <%= challenge.platform %>
      </div>
      <div class="card-stake">
        £<%= challenge.stake %>
      </div>
      <div class="card-description text-center">
        <div class="challenge-info">
        <% if challenge.host.photo? %>
          <%= image_tag "logo.png", alt: "alttext", class: "challenge-photo" %>
          <% else %>
          <%= cl_image_tag challenge.host.photo, class: "challenge-photo" %>
          <% end %>
          <div class= "text-play">
            <p>Play</p>
          </div>
          <div class= "text-host">
            <span><%= challenge.host_gamertag %></span>
          </div>
          <div class= "text-play">
            <p>at</p>
          </div>
        </div>
        <div class= "text-challenge">
          <p><%= challenge.game %></p>
        </div>
      </div>
    </div>
  </div>
</a>

<!-- <div class="card">
  <div class="card-body" style="background-image: url(<%= challenge.photo %>);">
    <div class="card-platform">
      <#%= challenge.platform %>
    </div>
    <div class="card-stake">
      £<#%= challenge.stake %>
    </div>
    <div class="card-description text-center">
      <span>User Online:<#%= challenge.host.online? %></span>
</div>
</div> -->

<!--   </div> -->

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_challengeform.html.erb
<div class="form-container">
  <%= simple_form_for @challenge do |f| %>
    <div class="gamertag"><%= f.input :host_gamertag, placeholder: 'Enter your gamertag', label: false, input_html: { class: "input-fields" } %></div>
    <div class="dropdowns">
      <div class="game">
        <%= f.input :stake, placeholder: 'Choose stake', label: false, input_html: { class: "input-fields" } %>
      </div>
      <div class="game">
        <%= f.input :game, collection: ["COD", "CS:GO", "Fifa", "Fortnite"], label: false, input_html: { class: "input-fields" } %>
      </div>
      <div class="game">
        <%= f.input :platform, collection: ["PS4", "XBOX", "PC"], label: false, input_html: { class: "input-fields" } %>
      </div>
    </div>
    <div class="form-desc">
      <%= f.input :description, placeholder: 'Describe your event', label: false, input_html: { class: "input-fields" } %>
    </div>
    <div class="form-btn">
      <%= f.button :submit, class: "btn btn-primary rounded", id:"form-btn" %>
    </div>
    <div id="deposit-alert"></div>
  <% end %>
</div>
<script>
  var stake = document.getElementById("challenge_stake");
  console.log(stake);
  var button = document.getElementById("form-btn");
  stake.addEventListener("keyup", (event) => {
    if (stake.value > <%= current_user.balance %> && <%= @challenge.guest.nil? %>) {
      document.getElementById("deposit-alert").innerHTML = 'You do not have enough money in your account, please deposit ' + '<%= link_to "here", new_deposit_path %>'
      button.disabled = true;
      button.style.opacity = 0.2;
    } else {
      document.getElementById("deposit-alert").innerHTML = "";
      button.disabled = false;
      button.style.opacity = 1;
    }
    });
</script>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_confirmmodal.html.erb
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dimensions" role="document">
    <div class="modal-content">
      <div class="mikes-modal">
        <div class="modal-information">
          <div class="title">
            <h1>Almost there...</h1>
          </div>
          <div class="text-body">
            <p>You are about to put your money where your mouth is..</p>
            <p>Game: <%= @challenge.game %></p>
            <p>Platform: <%= @challenge.platform %></p>
            <h1>Game on...</h1>
          </div>
          <div class="price">
            <h1><%= humanized_money_with_symbol(@challenge.stake) %></h1>
          </div>
          <div class="modal-btns" id="disable">
            <%= link_to "Let's go!", challenge_set_guest_path(@challenge), class: 'btn btn-primary form-btn' %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
        <div class="modal-image">
          <%= cl_image_tag @challenge.photo %>
        </div>
      </div>
    </div>
  </div>
</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <div class="footer-social-media">
 <p><i class="fab fa-facebook-square"></i></p>
 <p><i class="fab fa-twitter-square"></i></p>
 <p><i class="fab fa-medium"></i></p>
 <p><i class="fab fa-twitch"></i></p>
    </div>

<div class= "footer-columns">
    <div class= "footer-column lonely-items">
      <div class= "logo-bettrplay">
      <%= image_tag "logo.png", class: "footer-logo" %>
      <p>Bettrplay</p>
    </div>
    </div>
    <div class= "center-columns">
    <div class="footer-column">
      <p>Office locations</p>
      <p>Management</p>
      <p>Public Relations</p>
    </div>
    <div class="footer-column">
      <p>Company information</p>
      <p>Investors relations</p>
      <p>Media & Press</p>
    </div>
    <div class="footer-column">
      <p>Recruitment</p>
      <p>Career opportunities</p>
    </div>
  </div>
    <div class="footer-column text-right lonely-items ">
      <p> <i class="fas fa-globe"></i> Languages:</p>
      <p>English</p>
      <p>Terms of use</p>
      <p>Contact us</p>
    </div>
  </div>

    <div class="footer-down">
      <p>© 2018 Bettrplay. All Rights Reserved.</p>
      <p>Bettrplay, Bettrplay.com and the Bettrplay logo are trademarks of Betterplay Company in the U.K and/or other countries.</p>
    </div>
  </div>
</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_homebanner.html.erb
<div class="container-fluid homepage-banner">
  <div class="homepage-slogan text-center">
    <%= image_tag "white_logo.png", height: '220', width: '188', alt: "bettrplay logo" %>
    <h3>Win Money Playing Your Favourite Video Games!</h3>
    <%= link_to "Challenges", challenges_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_lost_page.html.erb
<div class="container wonpage-container">
  <div class="row">
    <hr>
    <div class="col-xs-4 text-center">
      <h1>
        You lost this!
      </h1>
      <hr>
      <h2>
        You lost <strong>£<%= @challenge.stake %></strong>
      </h2>
    </div>
    <div class="col-xs-8 text-center">
      <img src="https://res.cloudinary.com/dcqopgfjo/image/upload/v1542981739/loser.png" style="width: 300px" alt="">

    </div>
    </div>
    <hr>
  </div>
</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_navbar.html.erb
  <!-- Right Navigation -->
<div class="navbar-wagon">
  <!-- Logo -->

  <% if current_user.nil? %>

    <%= link_to '/', class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>
  <% else %>
    <%= link_to challenges_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo.png", height: 50 %>
    <% end %>
  <% end %>
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <div class="nav-link-div">
        <%= link_to challenges_path do %>
          <i class="fab fa-searchengin"></i>
          Find Challenge
        <% end %>
      </div>

      <div class="nav-link-div">
        <%= link_to new_challenge_path do %>
          <i class="fas fa-gamepad"></i></i>
          Create Challenge
        <% end %>
      </div>



      <% unless current_user.messages.empty?%>

        <% if current_user.messages.all?(&:read?)%>

        <div class="nav-link-div">
          <%= link_to chatroom_path(Chatroom.where(receiver: current_user).or(Chatroom.where(sender: current_user)).first) do %>

            <i class="fas fa-comments"></i>
            Messages

          <% end %>
        </div>

        <% else %>

          <div class="nav-link-div">
            <%= link_to chatroom_path(Chatroom.where(receiver: current_user).or(Chatroom.where(sender: current_user)).first) do %>
              <div class="message-nav-new">
                <i class="fas fa-comments"></i>
                Messages
                <p class="notify-msg"><%= current_user.messages.where(read: false).count %></p>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <div class="nav-link-div">
      <%= link_to my_challenges_user_path(current_user) do %>
      <i class="fas fa-fire"></i></i>
      My Challenges
      <% end %>
    </div>

    <div class="nav-link-div">
      <%= link_to new_deposit_path do %>
      <i class="fas fa-money-bill-alt"></i>
      <%= "#{humanized_money_with_symbol(current_user.balance)}" %>
      <% end %>
    </div>


   </div>






    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user.photo? %>
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag "https://vanderbiltc4e.com/wp-content/uploads/2017/08/Super-Mario-Avatar-500x500-300x300.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to user_path(current_user) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <!--  -->
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login link (when logged out) -->

      <div class="nav-link-div">
        <%= link_to about_path do %>
          <i class="far fa-question-circle"></i>
          <%= "About" %>
        <% end %>
      </div>

      <div class="nav-link-div">
        <%= link_to new_user_session_path do %>
          <i class="fas fa-sign-in-alt"></i>
          <%= "#{t(".sign_in", default: "Login")}" %>
        <% end %>
      </div>
  </div>
<% end %>
</div>


  <!-- Dropdown list appearing on mobile only -->
<!--   <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div> -->

<!--       <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%#= t(".settings", default: "Settings") %>
              <#% end %>
            </li> -->

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_navbar_home.html.erb
<div class="navbar-wagon-home">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 60 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right-home hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <div class="nav-link-div-home">
      <%= link_to challenges_path do %>
      <i class="fab fa-searchengin"></i>
      Find Challenge
      <% end %>
      </div>

      <div class="nav-link-div-home">
      <%= link_to new_deposit_path do %>
      <i class="fas fa-money-bill-alt"></i>
      <%= "#{humanized_money_with_symbol(current_user.balance)}" %>
      <% end %>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo? %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
             <% else %>
              <%= image_tag "https://vanderbiltc4e.com/wp-content/uploads/2017/08/Super-Mario-Avatar-500x500-300x300.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
              <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login link (when logged out) -->

      <div class="nav-link-div-home">
      <%= link_to about_path do %>
      <i class="far fa-question-circle"></i>
      <%= "About" %>
      <% end %>
      </div>

      <div class="nav-link-div-home">
      <%= link_to new_user_session_path do %>
      <i class="fas fa-sign-in-alt"></i>
      <%= "#{t(".sign_in", default: "Login")}" %>
      <% end %>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_profilebanner.html.erb
<div class="banner-profile">
  <div class="profile-info">
    <img src="https://cyancatyt.weebly.com/uploads/4/8/6/0/48608097/9895818_orig.png" alt="">
  </div>
</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_results.html.erb
<div class="challenge-results">
  <% if @challenges.empty? %>
    <div class="jumbotron">
      <h1 class="display-4">No challenge found!</h1>
      <p class="lead">Click below button to see all available challenges to join.</p>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="/challenges" role="button">All challenges</a>
      </p>
    </div>
  <% else %>
    <div class="row">
      <% @challenges.each do |challenge| %>
      <div class="col-xs-4">
        <%= render "shared/card", challenge: challenge %>
      </div>

      <% end %>
    </div>

  <% end %>



</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_sidebar.html.erb
<div class="row">
  <div class="sidebar">
    <div class="row search-gamer-tag">
      <div class="col-xs-12">
        <h4 class="sidebar-card-title">Games</h4>
        <%= form_tag(challenges_path, method: "get") do %>
        <div class="col-xs-12 games-list">
          <%= radio_button_tag(:game, "CS:GO") %>
          <%= label_tag(:game, "CS:GO", class: "margin-right") %><span class="float-right badge round"><%=  @challenges.where(game: "CS:GO").count%></span>
        </div>
        <div class="col-xs-12 games-list">
          <%= radio_button_tag(:game, "Fifa") %>
          <%= label_tag(:game, "Fifa", class: "margin-right") %><span class="float-right badge round"><%=  @challenges.where(game: "FIFA").count%></span>
        </div>
        <div class="col-xs-12 games-list">
          <%= radio_button_tag(:game, "FortNite") %>
          <%= label_tag(:game, "FortNite", class: "margin-right") %><span class="float-right badge round"><%=  @challenges.where(game: "FortNite").count%></span>
        </div>
        <div class="col-xs-12 games-list">
          <%= radio_button_tag(:game, "COD") %>
          <%= label_tag(:game, "COD", class: "margin-right") %><span class="float-right badge round"><%=  @challenges.where(game: "COD").count%></span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="min-max">
          <%= text_field_tag :min, params[:min], placeholder: "Min", class: "form-control min-field" %>
          <%= text_field_tag :max, params[:max], placeholder: "Max", class: "form-control max-field" %>
        </div>
      </div>

    </div>
    <div class="row">
      <div class="col-md-12">
        <%= text_field_tag :tag, params[:tag], placeholder: "#Gamer Tag", class: "form-control search-gamer-tag" %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-6">
        <%= submit_tag "Search", class: "btn btn-primary search-gamer-tag" %>
      </div>
      <div class="col-xs-6">
        <%= link_to("Clear", challenges_path, class: "btn btn-link search-gamer-tag") %>
        <% end %>
      </div>

    </div>
    </div>
 <!-- form-check.// -->

</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_ticker.html.erb
<% @activities_all = PublicActivity::Activity.order("updated_at desc") %>
<% @activities = @activities_all.select { |a| a.key == "challenge.create" || a.key == "challenge.accepted" || a.key == "challenge.won" } %>
<% @activity_array = [] %>
<% @activities.last(15).each do |activity| %>
<% if activity.key == 'challenge.create' && activity.owner && activity.trackable.game %>
<% @activity_array << "#{activity.owner.username} added a challenge for #{activity.trackable.game} at £#{activity.trackable.stake} \u{1f60e} || " %>
<% elsif activity.key == '  challenge.accepted' && activity.owner && activity.trackable.game %>
<% @activity_array << "#{activity.owner.username} accepted a challenge for #{activity.trackable.game} at £#{activity.trackable.stake} \u{1f91d} || " %>
<% elsif activity.key == 'challenge.won' && activity.owner  && activity.trackable.game %>
<% @activity_array << "#{activity.owner.username} won a challenge for #{activity.trackable.game} at £#{activity.trackable.stake} \u{1f911} || " %>
<% else %>
<% @activity_array << "Deposits bonus of £5 for Xmas - Back Yourself! \u{1f385} || " %>
<% end %>
<% end %>

<div class="marquee">
  <% 100.times do |p| %>
  <p><%= @activity_array.join %></p>
  <% end %>
</div>

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/shared/_won_page.html.erb
<div class="container wonpage-container">
  <div class="row">
    <hr>
    <div class="col-xs-4 text-center">
      <h1>
        You won this!
      </h1>
      <hr>
      <h2>
        You won <strong>£<%= @challenge.stake %></strong>
      </h2>
    </div>
    <div class="col-xs-8 text-center">
      <img src="https://res.cloudinary.com/dcqopgfjo/image/upload/v1542980872/undraw_winners_2yls.svg" style="width: 66%" alt="">

    </div>
    </div>
    <hr>
  </div>
</div>