BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  devise_for :users
  resources :users, only: [:show] do
    member do
      get 'my_challenges', to: 'challenges#my_challenges'
    end
  end
  resources :users, only: [:show]
  resources :disputes, only: [:new]
  resources :deposits, only: [:new, :create] do
    resources :payments, only: [:new, :create]
  end
  resources :challenges do
    get 'host_win', to: 'challenges#host_win', as: :host_win
    get 'host_lost', to: 'challenges#host_lost', as: :host_lost
    get 'set_guest', to: 'challenges#set_guest', as: :set_guest
    get 'guest_left', to: 'challenges#guest_left', as: :guest_left
    member do
      patch 'add_time', to: 'challenges#add_time'
      patch 'leave', to: 'challenges#leave'
    end
  end
  resources :chatrooms do
    resources :messages
  end
  resources :activities

  mount ActionCable.server => "/cable"
  #do
  #  resources :disputes, only: [:new, :create, :show, :delete]
  #end
  # post '/challenges/:id/', to: 'challenges#set_guest', as:
end

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :user
  monetize :amount_cents
end

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  def new
    @deposit = Deposit.new
  end

  def create
    deposit = Deposit.create!(state: 'pending', amount: params[:amount], user: current_user)
    redirect_to new_deposit_payment_path(deposit)
  end

  def update
    @deposit = Deposit.find(params[:deposit_id])
    @deposit.update(strong_params)
  end

  private

  def strong_params
    params.require(:deposit).permit(:state, :payment)
  end
end

BettrPlay-da1b93a21d9daaa39939834c55805e5ec140519a/app/views/deposits/new.html.erb
<div class="container-deposit">
  <div class="deposit-form-container">
    <div class="deposit-form">
  <h1>Deposit</h1>
      <%= form_tag deposits_path(@deposit), id:"deposit-form" do %>
        <p>Input the amount you would like to deposit</p>
        <div class="row"><%= number_field_tag('amount', value = 0, options = { min: 1, max: 3000 }) %></div>
        <div class="row"><%= submit_tag 'Deposit', class: 'btn btn-primary', class: "desposit-btn"  %></div>
      <% end %>
    </div>
  </div>
  <img src="https://upload.wikimedia.org/wikipedia/commons/5/5a/SNES-controller.png" alt="">
</div>